# -*- coding: utf-8 -*-
"""Exploratory Data Analysis(EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IJsWvEm4_blmCpXMOfsM9VMmW6PXaoM

#The banking data is used for EDA project
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""#Data Exploration"""

df=pd.read_csv('/content/bank-dataset-use-for-marketing.csv',sep=';')
df.head(5)

df.shape
df.tail(6)

df.columns

print(df.info())

df.describe()

df["y"].value_counts()

df["marital"].value_counts(normalize = True)

"""#Sorting"""

df.sort_values(by = "duration", ascending = False).head()

df.apply(np.max)

df.sort_values(by = ["age", "duration"], ascending = [True, False]).head()

d = {"no": 0, "yes": 1}
df["y"] = df["y"].map(d)
df.head()

df[df["y"] == 1].select_dtypes(include='number').mean()

acd = round(df[df["y"] == 1]["duration"].mean(), 2)
acd_in_min = acd // 60
print("Average call duration for attracted clients =", acd_in_min, "min", int(acd) % 60, "sec")

df[-1:]

pd.crosstab(df["y"], df["marital"])

df.pivot_table(
    ["age", "duration"],
    ["job"],
    aggfunc = "mean",
).head(10)

"""#Visualization"""

pd.plotting.scatter_matrix(
    df[["age", "duration", "campaign"]],
    figsize = (15, 15),
    diagonal = "kde")
plt.show()

import matplotlib.pyplot as plt
plt.scatter(df["age"], df["campaign"]) # Assuming you want to plot 'age' against 'duration'
plt.xlabel("Age")
plt.ylabel("Campaign")
plt.title("Scatter Plot of Age vs Campaign")
plt.show()